name: Job Portal CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run basic demo step
        run: echo "✅ Basic pipeline executed successfully"
